(()=>{
  const ROAD=document.getElementById('road');
  if(!ROAD||document.getElementById('packing')) return;

  const css=`.packintro{font-size:11px;line-height:1.55;color:var(--mut);margin:0 3px 10px}.packstatus{background:var(--card);border:1px solid var(--ln);border-radius:16px;padding:12px;margin-bottom:10px}.packtop{display:flex;justify-content:space-between;gap:10px;align-items:center;font-size:12px;font-weight:900}.packbar{height:8px;background:#ece8df;border-radius:999px;overflow:hidden;margin-top:8px}.packfill{height:100%;width:0;background:var(--ac);transition:width .2s}.packreset{border:0;background:none;color:var(--mut);font-size:11px;text-decoration:underline}.packgroups{display:grid;gap:8px}.packgroup{background:var(--card);border:1px solid var(--ln);border-radius:16px;overflow:hidden}.packgroup summary{cursor:pointer;padding:12px 13px;font-weight:900;font-size:13px;list-style:none}.packgroup summary::-webkit-details-marker{display:none}.packitems{border-top:1px solid var(--ln);padding:6px 11px 10px}.packitem{display:flex;align-items:flex-start;gap:8px;padding:7px 2px;font-size:12px;line-height:1.35}.packitem input{margin-top:2px;transform:scale(1.12);flex:0 0 auto}.buythere{background:#fff6d9;border-radius:12px;padding:8px 9px;margin:5px 0;font-size:11px}.qty{color:var(--ac);font-weight:900}@media(min-width:620px){.packgroups{grid-template-columns:1fr 1fr}.packgroup.wide{grid-column:1/-1}}`;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);

  const lunch=document.createElement('section');
  lunch.innerHTML=`<div class="sec" id="lunch"><h2>מה אוכלים בצהריים? 🍽️</h2><span>בלי להסתבך כל יום</span></div><p style="font-size:11px;line-height:1.55;margin:0 3px 10px;color:var(--mut)">האסטרטגיה: 2 ארוחות מסעדה נחמדות, 1–2 צהריים מהירים במלון/לידו, ופעם אחת כריכים. כך לא נתקעים רעבים אבל גם לא בונים את כל היום סביב מסעדה.</p><div class="bank">
  <div class="place"><div class="placehead"><h3>🏨 מה יש במלון בצהריים?</h3><span>הכי קל אחרי טיול</span></div><p>במסעדות המלון אין צהריים מלאים רגילים לאורחים בודדים; <b>GalilON The Water</b> בבר הבריכה מגיש נשנושים וארוחות צהריים מהירות. זה Plan A טוב כשחוזרים עייפים.</p><div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="https://galilion.co.il/culinary/">🔗 מידע רשמי</a></div></div>
  <div class="place"><div class="placehead"><h3>🥪 כריכים מהחדר</h3><span>Plan B מצוין לטיולים</span></div><p>בחדרים יש מיני־מקרר, אז אפשר לקנות לחם, גבינות, ירקות ופירות ולהכין בבוקר. לא בונים על הוצאת אוכל מבופה ארוחת הבוקר בלי אישור מהמלון.</p><div class="chips"><span class="chip">🧊 מיני־מקרר</span><span class="chip">🎒 טוב לתל דן/שניר</span></div><div class="actions"><a class="btn" target="_blank" rel="noopener" href="https://galilion.co.il/rooms/">🔗 אבזור החדרים</a></div></div>
  <div class="place"><div class="placehead"><h3>א׳ · יום ההגעה</h3><span>גמיש לפי שעת היציאה</span></div><p>אם יוצאים בשעות הבוקר המאוחרות — אוכלים בדרך באחת מעצירות ההתרעננות. אם מגיעים כבר לאזור המלון: משהו קל ליד המלון או בר הבריכה אחרי הצ׳ק־אין.</p></div>
  <div class="place"><div class="placehead"><h3>ב׳ · אחרי תל דן</h3><span>ארוחת המסעדה של הטיול</span></div><p><b>דג על הדן</b> משתלב טבעי אחרי תל דן. אם הילדים גמורים — כריכים וחזרה ישר למלון.</p><div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="https://www.dagaldan.co.il/restaurant">🔗 אתר רשמי</a><a class="btn" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=Dag%20Al%20HaDan">📍 מפה</a></div></div>
  <div class="place"><div class="placehead"><h3>ג׳ · אגמון החולה</h3><span>אפס לוגיסטיקה</span></div><p>אוכלים משהו קל באזור אגמון/המלון אם פתוח בפועל, או חוזרים לבר הבריכה. לא נוסעים במיוחד למסעדה ביום הזה.</p></div>
  <div class="place"><div class="placehead"><h3>ד׳ · אחרי נחל שניר</h3><span>יום הכריכים</span></div><p><b>כריכים + פירות</b> מיד בסיום הטיול ואז חזרה למנוחה. אם דילגנו על דג על הדן ביום ב׳, אפשר להעביר אותו לכאן.</p><div class="chips"><span class="chip">🥪 הכי מהיר</span><span class="chip">😴 חוזרים מוקדם למנוחה</span></div></div>
  <div class="place"><div class="placehead"><h3>ה׳ · בדרך הביתה</h3><span>צהריים לפני הנסיעה</span></div><p>אחרי הפעילות האחרונה: <b>ג׳ויה ראש פינה</b>, ואז מתחילים את הדרך לרמת גן.</p><div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="https://joya.co.il/%D7%92%D7%95%D7%99%D7%94-%D7%A8%D7%90%D7%A9-%D7%A4%D7%99%D7%A0%D7%94/">🔗 אתר רשמי</a><a class="btn" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=Joya%20Rosh%20Pina">📍 מפה</a></div></div>
  </div>`;
  ROAD.before(lunch);

  try{
    const add=(date,event,afterName)=>{const d=D.find(x=>x.date===date);if(!d||d.ev.some(e=>e.n.includes('צהריים')))return;const idx=afterName?d.ev.findIndex(e=>e.n.includes(afterName)):-1;d.ev.splice(idx>=0?idx+1:d.ev.length,0,event)};
    add('2026-08-23',{t:'12:30',n:'צהריים בדרך / ליד המלון',desc:'לפי שעת היציאה: עצירת הדרך או משהו קל ליד המלון.',tags:['low']});
    add('2026-08-24',{t:'12:00',n:'צהריים: דג על הדן / כריכים',desc:'אם יש כוח למסעדה — דג על הדן; אחרת כריכים וחזרה.',tags:['low']},'תל דן');
    add('2026-08-25',{t:'12:00',n:'צהריים: ליד המלון / בר הבריכה',desc:'הכי קרוב והכי פשוט ביום הזה.',tags:['low']},'בריכה / מרכז המבקרים');
    add('2026-08-26',{t:'11:45',n:'צהריים: כריכים / דג על הדן',desc:'Plan A כריכים ופירות; דג על הדן אם דילגנו עליו ביום ב׳.',tags:['low']},'נחל שניר');
    add('2026-08-27',{t:'13:00',n:'צהריים בג׳ויה ראש פינה',desc:'ארוחה מסודרת לפני הדרך לרמת גן.',tags:['low']},'בית אוסישקין / אגמון');
    render();
  }catch(e){console.warn('Lunch timeline enhancement skipped',e)}

  const groups=[
    ['👨‍👩‍👧‍👦 בגדים — הורים',[
      ['a-shirts','חולצות קצרות — <span class="qty">10</span> (5 לכל הורה)'],['a-bottoms','מכנסיים קצרים/קלילים — <span class="qty">8</span> (4 לכל הורה)'],['a-underwear','תחתונים — <span class="qty">12</span> (6 לכל הורה)'],['a-socks','זוגות גרביים — <span class="qty">8</span> (4 לכל הורה)'],['a-pj','סט פיג׳מה — <span class="qty">2</span>'],['a-layer','שכבה דקה לערב/מזגן — <span class="qty">2</span>'],['a-swim','בגדי ים — <span class="qty">4</span> (2 לכל הורה)'],['a-hat','כובעים — <span class="qty">2</span>'],['a-shoes','נעלי הליכה סגורות — <span class="qty">2 זוגות</span>'],['a-sandals','סנדלים/כפכפים — <span class="qty">2 זוגות</span>']]],
    ['👦👦 בגדים — ילדים 3 ו־5',[
      ['k-shirts','חולצות קצרות — <span class="qty">14</span> (7 לכל ילד)'],['k-bottoms','מכנסיים קצרים — <span class="qty">12</span> (6 לכל ילד)'],['k-underwear','תחתונים — <span class="qty">16</span> (8 לכל ילד; אקסטרה לטיולי מים)'],['k-socks','זוגות גרביים — <span class="qty">10</span>'],['k-pj','סטים של פיג׳מות — <span class="qty">4</span> (2 לכל ילד)'],['k-layer','עליוניות דקות — <span class="qty">2</span>'],['k-swim','בגדי ים — <span class="qty">4</span> (2 לכל ילד)'],['k-hat','כובעי שמש — <span class="qty">2</span>'],['k-watershoes','נעלי מים/סנדלים להרטבה — <span class="qty">2 זוגות</span>'],['k-shoes','נעלי הליכה סגורות — <span class="qty">2 זוגות</span>'],['k-sandals','סנדלים/כפכפים — <span class="qty">2 זוגות</span>'],['k-night','חיתולי לילה/פולאפס — <span class="qty">5–6 לכל ילד שרלוונטי לו</span> (אם בכלל)']]],
    ['💦 בריכה, נחלים ושמש',[
      ['sun-body','קרם הגנה גוף SPF גבוה — <span class="qty">2 × 200 מ״ל</span>'],['sun-face','קרם הגנה לפנים — <span class="qty">1</span>'],['repellent','דוחה יתושים — <span class="qty">1–2</span>'],['aftersun','אפטר־סאן/אלוורה — <span class="qty">1</span>'],['towels','מגבות מיקרופייבר לטיולים מחוץ למלון — <span class="qty">4</span>'],['float','מצופי שחייה/ווסט לילדים — <span class="qty">2</span> אם משתמשים'],['goggles','משקפי שחייה — <span class="qty">2</span>'],['wetbags','שקיות לבגדי ים רטובים — <span class="qty">2–3</span>'],['poolbag','תיק בריכה/מים — <span class="qty">1</span>']]],
    ['🎒 טיולי יום',[
      ['daypacks','תיקי יום — <span class="qty">2</span> למבוגרים'],['bottles','בקבוקי שתייה רב־פעמיים — <span class="qty">4</span> (2×750 מ״ל + 2×500 מ״ל)'],['waterbackup','מים לגיבוי ברכב — <span class="qty">2 × 1.5 ל׳</span> בכל יציאה'],['picnic','מחצלת קטנה/שמיכת פיקניק — <span class="qty">1</span>'],['stroller','טיולון קל — <span class="qty">1</span> אם בן ה־3 עדיין משתמש בטיולים ארוכים'],['wipes-trip','מגבונים — <span class="qty">2 חבילות</span>'],['tissues','חבילות טישו קטנות — <span class="qty">4</span>'],['sanitizer','אלכוג׳ל — <span class="qty">2 קטנים</span>'],['zipbags','שקיות זיפלוק — <span class="qty">10</span>'],['sparekids','סט החלפה מלא לילדים בתיק — <span class="qty">2 סטים</span>']]],
    ['🥪 ערכת צהריים וכריכים',[
      ['cooler','צידנית רכה — <span class="qty">1</span>'],['ice','קרחומים — <span class="qty">4</span>'],['foodboxes','קופסאות אוכל — <span class="qty">4</span>'],['sandwichbags','שקיות סנדוויץ׳ — <span class="qty">10–12</span>'],['cutlery','סט סכו״ם רב־פעמי — <span class="qty">4</span>'],['napkins','מפיות — <span class="qty">20–30</span>'],['bars','חטיפי אנרגיה/גרנולה — <span class="qty">12</span>'],['crackers','קרקרים/בייגלה — <span class="qty">2 חבילות</span>'],['kidsnacks','חטיפים אישיים לילדים — <span class="qty">10–12</span>'],['fruitpouch','מחיות/פאוצ׳ים — <span class="qty">6</span> אם אוהבים']]],
    ['🛒 לקנות טרי בדרך/ליד המלון',[
      ['bread','לחם — <span class="qty">2 כיכרות</span> או <span class="qty">12 פיתות</span> (לכ־2 ארוחות כריכים)'],['cheese','גבינה — <span class="qty">400–500 גרם</span>'],['hummus','חומוס — <span class="qty">400–500 גרם</span>'],['veg','מלפפונים — <span class="qty">6</span> + עגבניות/שרי — <span class="qty">2 קופסאות</span>'],['fruit','פירות — <span class="qty">16–20 יחידות</span>'],['yogurt','יוגורטים/מעדנים — <span class="qty">8</span> אם נכנס במיני־מקרר'],['spread','ממרח שילדים אוהבים — <span class="qty">1</span>'],['milk','חלב קטן/משקה אהוב — <span class="qty">1–2</span> לפי הצורך']]],
    ['🧼 רחצה וטיפוח',[
      ['brushes','מברשות שיניים — <span class="qty">4</span>'],['paste','משחת שיניים — <span class="qty">1–2</span>'],['shampoo','שמפו — <span class="qty">1</span>'],['conditioner','מרכך — <span class="qty">1</span> אם צריך'],['soap','סבון/תחליב רחצה — <span class="qty">1</span>'],['deodorant','דאודורנט — <span class="qty">2</span>'],['brush','מברשת/מסרק שיער — <span class="qty">1</span>'],['razor','ציוד גילוח אישי — <span class="qty">לפי הצורך</span>'],['contact','עדשות/משקפיים + תמיסה — <span class="qty">לפי מי שצריך</span>']]],
    ['🩹 תרופות ועזרה ראשונה',[
      ['regularmeds','תרופות קבועות — <span class="qty">ל־7 ימים</span> (5 + 2 ימי גיבוי)'],['kidfever','משכך כאב/חום לילדים — <span class="qty">בקבוק 1</span> מהסוג שאתם כבר משתמשים בו'],['adultpain','משכך כאב למבוגרים — <span class="qty">חבילה 1</span>'],['thermometer','מדחום — <span class="qty">1</span>'],['bandages','פלסטרים — <span class="qty">10–15</span>'],['antiseptic','חומר/מגבוני חיטוי — <span class="qty">1</span>'],['antihistamine','תרופה לאלרגיה — <span class="qty">רק אם אתם משתמשים בה בדרך כלל</span>'],['prescriptions','תרופות מרשם/משאף/ציוד רפואי אישי — <span class="qty">לפי מי שצריך</span>']]],
    ['🔌 אלקטרוניקה ובידור',[
      ['phones','טלפונים — <span class="qty">2</span>'],['phonechargers','מטעני טלפון — <span class="qty">2</span>'],['carcable','מטען רכב + כבל — <span class="qty">1–2</span>'],['powerbank','סוללה ניידת — <span class="qty">1–2</span>'],['tablet','טאבלט — <span class="qty">1</span> (או 2 אם זה מה שעובד לכם בנסיעות)'],['headphones','אוזניות לילדים — <span class="qty">2</span>'],['downloads','להוריד מראש סרטים/פרקים/משחקים — <span class="qty">כמה שעות תוכן אופליין</span>'],['watchcharger','מטענים לשעונים/אוזניות — <span class="qty">לפי הצורך</span>'],['multicharger','מטען USB רב־יציאות — <span class="qty">1</span>']]],
    ['🧸 שינה, ילדים וחדר',[
      ['comfort','חפץ מעבר/בובה אהובה — <span class="qty">1 לכל ילד</span>'],['books','ספרי ערב — <span class="qty">2–3</span>'],['toys','צעצועים קטנים — <span class="qty">2–3 לכל ילד</span>'],['activity','ערכת ציור/מדבקות קטנה — <span class="qty">1</span>'],['nightlight','מנורת לילה — <span class="qty">1</span> אם רגילים'],['laundry','שקיות לכביסה מלוכלכת — <span class="qty">2</span>'],['trashbags','שקיות אשפה קטנות — <span class="qty">5</span>'],['shoppingbags','שקיות קניות רב־פעמיות — <span class="qty">2</span>'],['clips','אטבים לייבוש בגדי ים — <span class="qty">6–8</span>']]],
    ['🚗 לרכב ולדרך',[
      ['carseats','כיסאות בטיחות מחוברים ומכוונים — <span class="qty">2</span>'],['carsnack','קופסת חטיפים נגישה — <span class="qty">1</span>'],['carwipes','מגבונים ברכב — <span class="qty">1 חבילה</span>'],['cartrash','שקיות אשפה לרכב — <span class="qty">3–4</span>'],['vomitbags','שקיות הקאה — <span class="qty">4</span>'],['carspare','בגדי החלפה נגישים בלי לפתוח מזוודות — <span class="qty">סט 1 לכל ילד</span>'],['carwater','בקבוק מים גדול חירום — <span class="qty">1 × 1.5 ל׳</span>'],['sunshade','מגני שמש לחלונות — <span class="qty">אם אין כבר</span>']]],
    ['🪪 מסמכים ודברים שאסור לשכוח',[
      ['ids','תעודות זהות — <span class="qty">2</span>'],['booking','אישור הזמנה למלון — <span class="qty">דיגיטלי + צילום מסך</span>'],['bookings','אישורי הזמנות לאטרקציות — <span class="qty">לכל מה שסוגרים מראש</span>'],['wallets','ארנקים/כרטיסי אשראי — <span class="qty">2</span>'],['cash','מזומן קטן — <span class="qty">₪200–300</span>'],['keys','מפתחות בית + רכב — <span class="qty">סטים נדרשים</span>'],['insurance','פרטי קופת חולים/ביטוח נגישים בטלפון — <span class="qty">לכל בני המשפחה</span>']]]
  ];

  const packing=document.createElement('section');
  packing.id='packing';
  packing.innerHTML=`<div class="sec"><h2>רשימת אריזה ✅</h2><span>4 אנשים · 5 ימים / 4 לילות</span></div><p class="packintro">הכמויות מעט נדיבות בגלל חום, בריכה ונחלים. הסימונים נשמרים במכשיר.</p><div class="packstatus"><div class="packtop"><span id="packCount">0 / 0 ארוז</span><button id="packReset" class="packreset">אפס סימונים</button></div><div class="packbar"><div id="packFill" class="packfill"></div></div></div><div id="packGroups" class="packgroups"></div>`;
  ROAD.before(packing);
  const container=document.getElementById('packGroups');
  groups.forEach((g,idx)=>{
    const d=document.createElement('details');d.className='packgroup'+(g[0].startsWith('🛒')?' wide':'');if(idx<2)d.open=true;
    const note=g[0].startsWith('🛒')?'<div class="buythere">💡 עדיף לקנות טרי ביום הראשון/בדרך. הכמות מיועדת בעיקר ל־2 ארוחות כריכים ועוד נשנושים.</div>':'';
    d.innerHTML=`<summary>${g[0]}</summary><div class="packitems">${note}${g[1].map(x=>`<label class="packitem"><input type="checkbox" data-pack data-key="${x[0]}"><span>${x[1]}</span></label>`).join('')}</div>`;
    container.appendChild(d);
  });
  const boxes=[...document.querySelectorAll('[data-pack]')],count=document.getElementById('packCount'),fill=document.getElementById('packFill');
  const update=()=>{const n=boxes.filter(x=>x.checked).length;count.textContent=`${n} / ${boxes.length} ארוז`;fill.style.width=(boxes.length?Math.round(n/boxes.length*100):0)+'%'};
  boxes.forEach(b=>{b.checked=localStorage.getItem('pack-'+b.dataset.key)==='1';b.addEventListener('change',()=>{localStorage.setItem('pack-'+b.dataset.key,b.checked?'1':'0');update()})});
  document.getElementById('packReset').addEventListener('click',()=>{boxes.forEach(b=>{b.checked=false;localStorage.setItem('pack-'+b.dataset.key,'0')});update()});
  update();
})();
